# Server settings ：后面必须有空格
server:
    port: 9000
    address: localhost

# DATASOURCE
jdbc:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://192.168.56.101:3306/ssm?useUnicode=true&amp;charaterEncoding=utf-8
    databaseName: ssm
    serverName: 127.0.0.1
    username: root
    password: 111111
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true

# SPRING PROFILES
spring:       
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

# MyBatis
mybatis:
    typeAliasesPackage: com.je.demo.**.domain
    mapperLocations: classpath:com/je/demo/*/*/dao/mapper/*.xml
    configLocation: classpath:mybatis-config.xml

# LOGGING
logging:
    level:
       com.ibatis:INFO,DEBUG